/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollegesIndexRouteImport } from './routes/colleges.index'
import { Route as CollegesIdRouteImport } from './routes/colleges.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesIndexRoute = CollegesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollegesRoute,
} as any)
const CollegesIdRoute = CollegesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollegesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/compare': typeof CompareRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/colleges/': typeof CollegesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/colleges': typeof CollegesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colleges': typeof CollegesRouteWithChildren
  '/compare': typeof CompareRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/colleges/': typeof CollegesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colleges'
    | '/compare'
    | '/login'
    | '/saved'
    | '/signup'
    | '/colleges/$id'
    | '/colleges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/login'
    | '/saved'
    | '/signup'
    | '/colleges/$id'
    | '/colleges'
  id:
    | '__root__'
    | '/'
    | '/colleges'
    | '/compare'
    | '/login'
    | '/saved'
    | '/signup'
    | '/colleges/$id'
    | '/colleges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollegesRoute: typeof CollegesRouteWithChildren
  CompareRoute: typeof CompareRoute
  LoginRoute: typeof LoginRoute
  SavedRoute: typeof SavedRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/': {
      id: '/colleges/'
      path: '/'
      fullPath: '/colleges/'
      preLoaderRoute: typeof CollegesIndexRouteImport
      parentRoute: typeof CollegesRoute
    }
    '/colleges/$id': {
      id: '/colleges/$id'
      path: '/$id'
      fullPath: '/colleges/$id'
      preLoaderRoute: typeof CollegesIdRouteImport
      parentRoute: typeof CollegesRoute
    }
  }
}

interface CollegesRouteChildren {
  CollegesIdRoute: typeof CollegesIdRoute
  CollegesIndexRoute: typeof CollegesIndexRoute
}

const CollegesRouteChildren: CollegesRouteChildren = {
  CollegesIdRoute: CollegesIdRoute,
  CollegesIndexRoute: CollegesIndexRoute,
}

const CollegesRouteWithChildren = CollegesRoute._addFileChildren(
  CollegesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollegesRoute: CollegesRouteWithChildren,
  CompareRoute: CompareRoute,
  LoginRoute: LoginRoute,
  SavedRoute: SavedRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
